
rule download_data:
    output:
        "GSE100866_PBMC_vs_flow_10X-ADT_clr-transformed.csv.gz",
        "GSE100866_PBMC_vs_flow_10X-ADT_umi.csv.gz",
        "GSE100866_PBMC_vs_flow_10X-RNA_umi.csv.gz",
    shell:
        """
        wget "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE100866&format=file&file=GSE100866%5FPBMC%5Fvs%5Fflow%5F10X%2DADT%5Fclr%2Dtransformed%2Ecsv%2Egz" -O GSE100866_PBMC_vs_flow_10X-ADT_clr-transformed.csv.gz
        wget "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE100866&format=file&file=GSE100866%5FPBMC%5Fvs%5Fflow%5F10X%2DADT%5Fumi%2Ecsv%2Egz" -O GSE100866_PBMC_vs_flow_10X-ADT_umi.csv.gz
        wget "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE100866&format=file&file=GSE100866%5FPBMC%5Fvs%5Fflow%5F10X%2DRNA%5Fumi%2Ecsv%2Egz" -O GSE100866_PBMC_vs_flow_10X-RNA_umi.csv.gz
        """

rule parse_data:
    input:
        counts="GSE100866_PBMC_vs_flow_10X-RNA_umi.csv.gz",
        adt="GSE100866_PBMC_vs_flow_10X-ADT_umi.csv.gz",
        adt_clr="GSE100866_PBMC_vs_flow_10X-ADT_clr-transformed.csv.gz",
    output:
        loom=protected("data.loom"),
        ab="ab.txt.gz",
    script: "parse.py"

rule parse_data_cd4:
    input:
        loom=rules.parse_data.output.loom,
        ab=rules.parse_data.output.ab,
    output:
        loom=protected("cd4/data.loom"),
        ab="cd4/ab.txt.gz",
    script: "parse_cd4.py"

rule all:
    input:
        expand(rules.parse_data.output),
